/**
 * @author Elena Cantero Molina
 */
package GUIQytetet;

import modeloqytetet.*;

public class VistaQytetet extends javax.swing.JPanel {

    /**
     * Creates new form VistaQytetet
     */
    public VistaQytetet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaJugador1 = new GUIQytetet.VistaJugador();
        vistaCasilla1 = new GUIQytetet.VistaCasilla();
        vistaCartasSorpresa1 = new GUIQytetet.VistaCartasSorpresa();
        vistaJugador2 = new GUIQytetet.VistaJugador();
        vistaCasilla2 = new GUIQytetet.VistaCasilla();
        vistaCartasSorpresa2 = new GUIQytetet.VistaCartasSorpresa();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vistaJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vistaCasilla2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vistaCartasSorpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vistaCartasSorpresa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(vistaCasilla2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vistaJugador2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUIQytetet.VistaCartasSorpresa vistaCartasSorpresa1;
    private GUIQytetet.VistaCartasSorpresa vistaCartasSorpresa2;
    private GUIQytetet.VistaCasilla vistaCasilla1;
    private GUIQytetet.VistaCasilla vistaCasilla2;
    private GUIQytetet.VistaJugador vistaJugador1;
    private GUIQytetet.VistaJugador vistaJugador2;
    // End of variables declaration//GEN-END:variables

    public void actualizar(Qytetet aux){
        vistaCasilla2.actualizar(aux.getJugadorActual().getCasillaActual().toString());
        if(aux.getCartaActual() != null)
            vistaCartasSorpresa2.actualizar(aux.getCartaActual().toString());
        else
            vistaCartasSorpresa2.actualizar("No hay carta actual\n");
       
        vistaJugador2.actualizar(aux.getJugadorActual().toString());
        this.repaint();
        this.revalidate();
    }
}
