/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

/**
 *
 * @author usuario
 */
public class VistaCartasSorpresa extends javax.swing.JPanel {

    /**
     * Creates new form VistaCartasSorpresa
     */
    public VistaCartasSorpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtTextoCartasSorpresa = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtTextoCartasSorpresa.setEditable(false);
        jtTextoCartasSorpresa.setColumns(20);
        jtTextoCartasSorpresa.setFont(new java.awt.Font("Comic Sans MS", 2, 12)); // NOI18N
        jtTextoCartasSorpresa.setForeground(new java.awt.Color(255, 0, 112));
        jtTextoCartasSorpresa.setRows(5);
        jtTextoCartasSorpresa.setText("Carta Sorpresa actual");
        jScrollPane1.setViewportView(jtTextoCartasSorpresa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtTextoCartasSorpresa;
    // End of variables declaration//GEN-END:variables

    public void actualizar(String descripcionCartaSorpresa){
        this.jtTextoCartasSorpresa.setText(descripcionCartaSorpresa);
        this.repaint(); //Investiga para qué sirven estos métodos
        this.revalidate();
    }
}
